---
# Due to simplicity of task the playbook is created as a single file
# Ansible Galaxy and Commmunity Docker collection is used for building custom docker image and running container

# While writing the script the examples from Ansible khowledge base were used. Particularly the examples from following 2 links:
# 1. https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#examples
# 2. https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#examples

- hosts: localhost
tasks:
  - name: Build docker image using Dockerfile
    community.docker.docker_image:
      name: nginx_image
      build:
        path: .
        args:
          listen_port: 80
      source: build
      tag: "v1"
      push: no

- name: Run docker container with Nginx webserver
    community.docker.docker_container: 
      name: nginx_container
      image: "nginx_image:v1"
      container_default_behavior: no_defaults
      ports:
        - "80:80"
      
